### PR TITLE
Updated Disqus Script + Absolute Url

### PR DESCRIPTION
**Pull request by HadenHiles**
Both disqus-pencilblue branches master and 0.5.0 do not work with the current version of Disqus.

This fork has the updated Disqus source from their website modified to use an absolute url for the disqus_config page.url so that the plugin works.

### CODE REVIEW

**Comment by markbaird** [comment]
The current branch of the disqus-pencilblue plugin is working fine for me. Are you sure there isn't an error in your site configuration? I'm not sure what you mean by "the current version of Disqus". It's true that they have recently restructured the JavaScript embed code slightly, but it doesn't look like a new version of Disqus. The old embed code still works.

**Comment by HadenHiles** [comment]
`^article_permalink^` isn't resolving to the full url and Disqus kept displaying the message "Unable to load Disqus".

I remember reading in their docs somewhere that the page.url needs to be absolute.

**Comment by markbaird** [comment]
It sounds like your issue probably stems from an invalid pb.config.siteRoot setting.

**Comment by HadenHiles** [comment]
If I have the siteRoot set to "/" would this break it?

**Comment by HadenHiles** [comment]
The website I am referring to is also deployed on openshift, if this makes any difference.

**Comment by HadenHiles** [comment]
@markbaird thanks for steering me in the right direction. I fixed my issue without having to change the source of the plugin!

**Comment by markbaird** [comment]
I have a blog deployed on OpenShfit and this plugin works fine on that site. I have `siteRoot` configured as 'https://www.mydomain.com'. You'll run into issues if you don't have your actual site root configured in `siteRoot`.

Also, you need to do this in order to properly use Disqus. If we use the value from `window.location.host` then going to your site using the OpenShift *.rhcloud.com URL will load one set of comments, and going to some custom domain you have configured for your site will load a different set of comments. If you had multiple custom domains configured for your site, different comments would load on each one. You want permalinks to be the definitive, preferred URL, and you get that by defining the preferred site root in PencilBlue's `siteRoot` setting.

**Comment by markbaird** [comment]
Glad I could help

**Pull request closed without merging**
